[master] github actions #3

diff --git a/.github/workflows/php.yml b/.github/workflows/php.yml
--- a/.github/workflows/php.yml
+++ b/.github/workflows/php.yml
@@ -55,15 +55,18 @@ jobs:
       - name: Install Composer dependencies
         run: composer install --no-progress --prefer-dist --optimize-autoloader
 
-      - name: Run Migration
+      - name: Run Migration and fixtures
         run: |
           php bin/console doctrine:schema:update --force || echo "No migrations found or schema update failed"
           php bin/console doctrine:migrations:migrate || echo "No migrations found or migration failed"
+          php bin/console doctrine:fixtures:load --append || echo "Fixtures error"
         env:
-          DATABASE_URL: postgres://potato:potato@potato-db:${{ job.services.postgres.ports[5432] }}/potato_test?charset=UTF-8
+          DATABASE_URL: postgres://potato:potato@localhost:${{ job.services.postgres.ports[5432] }}/potato_test?charset=UTF-8
 
       - name: Install PHPUnit
         run: simple-phpunit install
 
       - name: Run tests
-        run: simple-phpunit --coverage-text
+        run: simple-phpunit
+        env:
+          DATABASE_URL: postgres://potato:potato@localhost:${{ job.services.postgres.ports[5432] }}/potato_test?charset=UTF-8
